DROP TABLE IF EXISTS creatures;
DROP TABLE IF EXISTS fighters;

CREATE TABLE creatures(
id SERIAL4 PRIMARY KEY,
name VARCHAR(255),
fightable BOOLEAN,
fighter_id INT4
);

CREATE TABLE fighters(
id SERIAL4 PRIMARY KEY,
name VARCHAR(255)
);